PORTNAME=	zabbix54
PORTREVISION=	0
CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../${PORTNAME}-server
PLIST=		${PKGDIR}/pkg-plist.java

OPTIONS_DEFINE=		IPV6

USE_JAVA=	yes
ZABBIX_BUILD=	java

.include "${MASTERDIR}/Makefile"
